---
- hosts: all
  vars:
    hostvar: default
    var1: def
    var2: def
    var3: def
  remote_user: root
  tasks:
    - name: Touch File
      command: touch /tmp/ansible_was_here
      when: ansible_os_family == "RedHat"
    - debug:
	msg: "Var 1: {{ var1 }}, Var 2: {{ var2 }}, Var 3: {{ var3 }}, HostVar: {{ hostvar }}"

